#!/usr/bin/env python3
"""Execute Vertical Slice v1 Stage 2 semantics on frozen Stage 1 substrate.

This stage emits symbolic geometric constraints and terminal states only.
It does NOT synthesize physical acupoint coordinates.

Approved inputs:
- B v2.1 frozen graph
- Stage 1 approved substrate
- human-approved slice surface-expression registry
- human-approved slice B/F-cun calibration generated by the approved review builder

Legacy C coordinates are never read.
"""
from __future__ import annotations
import argparse,hashlib,json,re,subprocess
from pathlib import Path
from spatial_core import AtlasStore
from slice_surface_registry import REGISTRY_BY_ID, execute_all

B_SHA="8126e20938a478a2d214f4a8487cabeebc8f3115f7a81ad30e46b594958fb2c1"
COHORT=("HT7","LI4","ST1","GB14","GB23","LU6","LI7","GB26","ST2","ST10","LI18","LI17","BL17","BL23","BL25","BL40","TE20","ST4","TE6","ST9")
EXPECTED_GEOMETRY_BLOB="efb078aaecc08af1a4491cb40e9c84fd4e4443fa"
EXPECTED_REVIEW_BUILDER_BLOB="1c3a05ceb4b6f84ee670b6d6cf2c50c6f8349b5a"

STOP={"the","of","and","a","an","to","in","on","at","with","bone","muscle","border","aspect","region","space","line","centre","center","midpoint"}

SURFACE_RULES=(
 (("palmar wrist crease",),"SR:palmar_wrist_crease"),
 (("dorsal wrist crease",),"SR:dorsal_wrist_crease"),
 (("dorsum of the hand",),"SR:dorsum_hand"),
 (("anteromedial aspect","wrist"),"SR:anteromedial_wrist"),
 (("anterolateral aspect","forearm"),"SR:anterolateral_forearm"),
 (("posterolateral aspect","forearm"),"SR:posterolateral_forearm"),
 (("posterior aspect","forearm"),"SR:posterior_forearm"),
 (("posterior aspect","knee"),"SR:posterior_knee"),
 (("popliteal crease",),"SR:popliteal_crease"),
 (("posterior median line",),"SR:posterior_median_line"),
 (("midaxillary line",),"SR:midaxillary_line"),
 (("fourth intercostal space",),"SR:fourth_intercostal_space"),
 (("lateral thoracic region",),"SR:lateral_thorax"),
 (("lateral abdomen",),"SR:lateral_abdomen"),
 (("anterior region of the neck",),"SR:anterior_neck"),
 (("anterior aspect","neck"),"SR:anterior_neck"),
 (("upper back region",),"SR:upper_back"),
 (("lumbar region",),"SR:lumbar_region"),
 (("on the face",),"SR:face_region"),
 (("face",),"SR:face_region"),
 (("on the head",),"SR:head_region"),
 (("head",),"SR:head_region"),
 (("nasolabial sulcus",),"SR:nasolabial_sulcus"),
 (("interosseous space between the radius and the ulna",),"SR:radius_ulna_interosseous_space"),
)

REL_OP={
 "surface-landmark":"surface_membership",
 "relative-to":"directional_relation",
 "reference-acupoint":"reference_dependency",
 "same-level":"same_level_plane",
 "between":"between_constraint",
 "midpoint-of-entity":"entity_midpoint",
 "on-line":"line_membership",
 "center-of":"entity_center",
 "midpoint-between":"midpoint_between",
 "overlies":"overlies_projection",
}

def sha256(p:Path):
 h=hashlib.sha256()
 with p.open("rb") as f:
  for b in iter(lambda:f.read(1<<20),b""):h.update(b)
 return h.hexdigest()

def git_blob(path):
 return subprocess.check_output(["git","hash-object",path],text=True).strip()

def normtxt(s):
 return re.sub(r"[^a-z0-9]+"," ",(s or "").lower().replace("proxi-mal","proximal").replace("pos-terior","posterior")).strip()

def content_tokens(s):
 return [x for x in normtxt(s).split() if len(x)>2 and x not in STOP]

def atlas_lookup(store:AtlasStore,raw:str):
 toks=content_tokens(raw)
 if not toks:return {"status":"UNRESOLVED","reason":"no discriminating atlas-name tokens"}
 exact=[];partial=[]
 for p in store.atlas["parts"]:
  n=normtxt(p["name"])
  if all(t in n.split() for t in toks):exact.append((p["id"],p["name"]))
  elif all(t in n for t in toks):partial.append((p["id"],p["name"]))
 candidates=exact or partial
 # Multiple mesh parts with same canonical name/laterality are not silently collapsed.
 if len(candidates)==1:
  return {"status":"RESOLVED","geometry":{"kind":"atlas_part","part_id":candidates[0][0],"name":candidates[0][1]}}
 if len(candidates)>1:
  return {"status":"MULTIPLE","reason":"multiple atlas-name candidates","candidates":[{"part_id":a,"name":b} for a,b in candidates[:30]]}
 # Try concept names; a single concept may intentionally own multiple mesh parts.
 cc=[]
 for x in store.atlas["concepts"]:
  n=normtxt(x["name"])
  if all(t in n for t in toks):cc.append(x)
 if len(cc)==1 and cc[0].get("elements"):
  return {"status":"RESOLVED","geometry":{"kind":"atlas_concept","concept_id":cc[0]["id"],"name":cc[0]["name"],"part_ids":cc[0]["elements"]}}
 if len(cc)>1:
  return {"status":"MULTIPLE","reason":"multiple atlas-concept candidates","candidates":[{"concept_id":x["id"],"name":x["name"]} for x in cc[:30]]}
 return {"status":"UNRESOLVED","reason":"no unique atlas name match"}

def surface_registry_id(node,stmt_text):
 raw=normtxt(node.get("source_raw"))
 full=normtxt(stmt_text)
 # Node span is primary. Statement context is used only to disambiguate generic
 # aspect words such as "posterior aspect"; it must never cause an unrelated
 # landmark in the same sentence to inherit a surface mask.
 direct=(
  ("palmar wrist crease","SR:palmar_wrist_crease"),
  ("dorsal wrist crease","SR:dorsal_wrist_crease"),
  ("dorsum of the hand","SR:dorsum_hand"),
  ("popliteal crease","SR:popliteal_crease"),
  ("posterior median line","SR:posterior_median_line"),
  ("midaxillary line","SR:midaxillary_line"),
  ("fourth intercostal space","SR:fourth_intercostal_space"),
  ("lateral thoracic region","SR:lateral_thorax"),
  ("lateral abdomen","SR:lateral_abdomen"),
  ("upper back region","SR:upper_back"),
  ("lumbar region","SR:lumbar_region"),
  ("nasolabial sulcus","SR:nasolabial_sulcus"),
  ("interosseous space between the radius and the ulna","SR:radius_ulna_interosseous_space"),
 )
 for phrase,rid in direct:
  if phrase in raw:return rid
 if raw=="face":return "SR:face_region"
 if raw=="head":return "SR:head_region"
 if "anteromedial aspect" in raw and "wrist" in full:return "SR:anteromedial_wrist"
 if "anterolateral aspect" in raw and "forearm" in full:return "SR:anterolateral_forearm"
 if "posterolateral aspect" in raw and "forearm" in full:return "SR:posterolateral_forearm"
 if "posterior aspect" in raw and "forearm" in full:return "SR:posterior_forearm"
 if "posterior aspect" in raw and "knee" in full:return "SR:posterior_knee"
 if ("anterior region" in raw or "anterior aspect" in raw) and "neck" in full:return "SR:anterior_neck"
 return None

def parse_acupoint_ref(raw):
 m=re.search(r"\b(?:LU|LI|ST|SP|HT|SI|BL|KI|PC|TE|GB|LR|CV|GV)\s*\d+\b",(raw or "").upper())
 return re.sub(r"\s+","",m.group(0)) if m else None

def relation_direction(rel):
 cue=normtxt((rel.get("cue_span") or {}).get("source_raw"))
 table=("radial","ulnar","anterior","posterior","superior","inferior","medial","lateral","proximal","distal")
 for t in table:
  if t in cue:return t
 return None

def status_rank(s):
 return {"INVALID":5,"UNRESOLVED":4,"MULTIPLE":3,"CONDITIONAL":2,"RESOLVED":1}.get(s,9)

def main():
 ap=argparse.ArgumentParser()
 ap.add_argument("--graph",default="public/knowledge/anatomy-acupoint-relations-v2.1.json")
 ap.add_argument("--model-dir",default="public/models")
 ap.add_argument("--substrate",default=".tmp/c-v3-slice/spatial-substrate.json")
 ap.add_argument("--calibration",default=".tmp/c-v3-slice/review/calibration-draft.json")
 ap.add_argument("--approval",default="artifacts/c-v3/vertical-slice-v1/registry-calibration-approval.json")
 ap.add_argument("--out",default=".tmp/c-v3-slice/stage2-execution.json")
 args=ap.parse_args()
 gp=Path(args.graph)
 if sha256(gp)!=B_SHA:raise SystemExit("B v2.1 SHA mismatch")
 if git_blob("scripts/cv3/slice_surface_registry.py")!=EXPECTED_GEOMETRY_BLOB:raise SystemExit("approved geometry executor changed; renewed human review required")
 if git_blob("scripts/cv3/build_vertical_slice_review.py")!=EXPECTED_REVIEW_BUILDER_BLOB:raise SystemExit("approved review/calibration builder changed; renewed human review required")
 approval=json.loads(Path(args.approval).read_text())
 if approval.get("status")!="APPROVED":raise SystemExit("slice registry/calibration not human-approved")
 calibration=json.loads(Path(args.calibration).read_text())
 if len(calibration.get("rows",[]))!=12:raise SystemExit("approved calibration row count mismatch")
 cal={x["calibration_id"]:x for x in calibration["rows"]}
 g=json.loads(gp.read_text());store=AtlasStore(Path(args.model_dir));sub=json.loads(Path(args.substrate).read_text())
 surf=execute_all(store,sub)
 stmt={x["source_statement_id"]:x for x in g["source_statements"]}
 node={x["node_id"]:x for x in g["landmark_nodes"]}
 bindings={x["child_landmark_id"]:x for x in g.get("composite_bindings",[])}
 concept={x["id"]:x for x in store.atlas["concepts"]}
 all_point_ids={x["point_id"] for x in g["points"]}

 out={"schema_version":"1.0.0","artifact":"c-v3-vertical-slice-v1-stage2-semantic-execution","status":"GENERATED_NOT_VALIDATED",
      "scope":{"cohort":list(COHORT),"physical_coordinates_generated":False,"legacy_coordinate_input":False},
      "input_lock":{"b_sha256":B_SHA,"geometry_executor_blob":EXPECTED_GEOMETRY_BLOB,"review_builder_blob":EXPECTED_REVIEW_BUILDER_BLOB},
      "points":[]}
 for pid in COHORT:
  ss=[x for x in g["source_statements"] if x["point_id"]==pid]
  sm={x["source_statement_id"] for x in ss}
  lms=[x for x in g["landmark_nodes"] if x["point_id"]==pid]
  rels=[x for x in g["relation_instances"] if x["subject_node_id"]==f"P:{pid}"]
  pms=[x for x in g.get("proportional_measurements",[]) if x["source_statement_id"] in sm]
  conds=[x for x in g.get("conditions",[]) if x["source_statement_id"] in sm]

  lout={}
  # First pass: terminal entities / surface-registry geometry / references.
  for n in lms:
   nid=n["node_id"];sr=surface_registry_id(n,stmt[n["source_statement_id"]]["text_canonical"])
   if sr:
    res=surf[sr]
    lout[nid]={"status":res.status,"executor":"approved_surface_registry","geometry":{"kind":"surface_registry","registry_id":sr,"geometry_hash":res.geometry_hash()} if res.status=="RESOLVED" else None,
               "reason":res.notes[0] if res.notes else (None if res.status=="RESOLVED" else "approved registry unresolved")}
    continue
   disp=n.get("terminal_disposition")
   if disp=="resolved_fma":
    fid=n.get("fma_id");co=concept.get(fid)
    if co and co.get("elements"):
     lout[nid]={"status":"RESOLVED","executor":"fma_mesh","geometry":{"kind":"fma_concept","fma_id":fid,"concept_name":co["name"],"part_ids":co["elements"]}}
    else:lout[nid]={"status":"UNRESOLVED","executor":"fma_mesh","geometry":None,"reason":"FMA concept has no atlas mesh elements"}
   elif disp=="cross_reference":
    rid=n.get("cross_reference_point_id") or parse_acupoint_ref(n.get("source_raw",""))
    lout[nid]={"status":"RESOLVED" if rid in all_point_ids else "INVALID","executor":"reference_acupoint",
               "geometry":{"kind":"reference_acupoint","point_id":rid} if rid in all_point_ids else None,
               "reason":None if rid in all_point_ids else "reference point absent from B graph"}
   elif disp in ("registry_limited","specialized_anchor"):
    z=atlas_lookup(store,n.get("source_raw",""));lout[nid]={"executor":"atlas_name_resolution",**z}
   elif disp in ("source_backed_derived_unresolved","ambiguous_generic","parent_unresolved","blocked_by_context"):
    z=atlas_lookup(store,n.get("source_raw",""))
    if z["status"]=="RESOLVED":
     lout[nid]={"executor":"atlas_name_resolution",**z}
    else:lout[nid]={"status":"UNRESOLVED","executor":"explicit_unresolved_taxonomy","geometry":None,"reason":disp}
   elif n.get("landmark_class") in ("soft_tissue_feature","orifice_or_cavity","vessel","cartilage","muscle","tendon","bone.opening","bone.process_or_prominence","structure.part","bone.bone"):
    z=atlas_lookup(store,n.get("source_raw",""));lout[nid]={"executor":"atlas_name_resolution",**z}
   else:
    lout[nid]={"status":"UNRESOLVED","executor":"no_family_executor","geometry":None,"reason":f"unsupported landmark disposition/class: {disp}/{n.get('landmark_class')}"}

  # Second pass: source-backed composite child subfeatures can execute if parent executes.
  for n in lms:
   nid=n["node_id"]
   if nid not in bindings:continue
   b=bindings[nid];par=lout.get(b["parent_landmark_id"])
   if par and par["status"]=="RESOLVED":
    raw=normtxt(n.get("source_raw"))
    modifier=next((x for x in ("superior","inferior","proximal","distal","free","anterior","posterior","medial","lateral","center","centre") if x in raw),None)
    if modifier:
     lout[nid]={"status":"RESOLVED","executor":"composite_subfeature",
                "geometry":{"kind":"entity_subfeature","modifier":modifier,"parent_landmark_id":b["parent_landmark_id"]},
                "provenance":{"binding_id":b["binding_id"]}}

  mout={}
  for m in pms:
   cid=m["measurement_id"];row=cal.get(cid)
   if not row:
    mout[cid]={"status":"UNRESOLVED","executor":"approved_calibration","reason":"measurement absent from approved calibration"}
   elif not row.get("who_citation",{}).get("pdf_page"):
    mout[cid]={"status":"UNRESOLVED","executor":"approved_calibration","reason":"WHO page citation missing"}
   else:
    mout[cid]={"status":"RESOLVED","executor":"approved_calibration",
               "constraint":{"kind":"proportional_offset","value":m.get("value"),"unit":"F-cun" if str(m.get("unit")).lower()=="f-cun" else m.get("unit"),
                             "source_unit":m.get("unit"),"direction":m.get("direction"),"anchor_landmark_id":m.get("anchor_landmark_id"),
                             "who_pdf_page":row["who_citation"]["pdf_page"],"source_statement_id":m["source_statement_id"]}}

  cout={}
  for c in conds:
   raw=normtxt((c.get("source_span") or {}).get("source_raw"))
   incompatible=any(k in raw for k in ("head is turned","against resistance","auricle is folded","folded forwards","folded forward"))
   if c["condition_type"]=="body_position" and incompatible:
    st="CONDITIONAL";reason="condition requires pose incompatible with default BodyParts3D pose"
   elif c["condition_type"] in ("alternative","palpation_dependent"):
    st="CONDITIONAL";reason="branch preserved; not forced into default-pose primary computation"
   else:
    st="RESOLVED";reason=None
   cout[c["condition_id"]]={"status":st,"executor":"condition_contract","condition_type":c["condition_type"],"branch_id":c.get("branch_id"),"reason":reason}

  rout={}
  for r in rels:
   rid=r["relation_id"];op=REL_OP.get(r["relation_type"])
   if not op:
    rout[rid]={"status":"INVALID","executor":"relation_dispatch","reason":"relation family has no slice executor"};continue
   argsr=[lout.get(x,{"status":"INVALID","reason":"missing argument output"}) for x in r.get("argument_node_ids",[])]
   worst=sorted((x["status"] for x in argsr),key=status_rank,reverse=True)[0] if argsr else "RESOLVED"
   if worst in ("INVALID","UNRESOLVED","MULTIPLE"):
    rout[rid]={"status":worst,"executor":op,"reason":"argument landmark not uniquely executable","argument_node_ids":r.get("argument_node_ids",[])};continue
   constraint={"op":op,"argument_node_ids":r.get("argument_node_ids",[]),"source_statement_id":r["source_statement_id"],"branch_id":r.get("branch_id")}
   if r["relation_type"]=="relative-to":
    direction=relation_direction(r)
    if not direction:
     rout[rid]={"status":"UNRESOLVED","executor":op,"reason":"direction cue not normalized","argument_node_ids":r.get("argument_node_ids",[])};continue
    constraint["direction"]=direction
   rout[rid]={"status":"RESOLVED","executor":op,"constraint":constraint}

  statements=[]
  for s in ss:
   sid=s["source_statement_id"]
   rel_ids=[r["relation_id"] for r in rels if r["source_statement_id"]==sid]
   mea_ids=[m["measurement_id"] for m in pms if m["source_statement_id"]==sid]
   con_ids=[c["condition_id"] for c in conds if c["source_statement_id"]==sid]
   statuses=[rout[x]["status"] for x in rel_ids]+[mout[x]["status"] for x in mea_ids]
   # Condition branches are reported separately; they do not downgrade an otherwise executable primary statement.
   base="RESOLVED" if not statuses else sorted(statuses,key=status_rank,reverse=True)[0]
   statements.append({"source_statement_id":sid,"section":s["section"],"status":base,
                      "relation_ids":rel_ids,"measurement_ids":mea_ids,"condition_ids":con_ids})

  loc=[x for x in statements if x["section"]=="location"]
  primary=loc[0]["status"] if loc else "UNRESOLVED"
  out["points"].append({"point_id":pid,"primary_location_status":primary,
    "landmarks":lout,"relations":rout,"measurements":mout,"conditions":cout,"statements":statements})

 q=Path(args.out);q.parent.mkdir(parents=True,exist_ok=True);q.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n")
 from collections import Counter
 print(json.dumps({"status":out["status"],"points":len(out["points"]),
   "primary_location_status":dict(Counter(x["primary_location_status"] for x in out["points"])),
   "landmark_status":dict(Counter(v["status"] for x in out["points"] for v in x["landmarks"].values())),
   "relation_status":dict(Counter(v["status"] for x in out["points"] for v in x["relations"].values())),
   "measurement_status":dict(Counter(v["status"] for x in out["points"] for v in x["measurements"].values())),
   "condition_status":dict(Counter(v["status"] for x in out["points"] for v in x["conditions"].values()))}))
if __name__=="__main__":main()
