import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
import {anatomySearchTerms} from '@/lib/anatomy-knowledge';
import type {Acupoint,AcupointCoordinate,AnatomyAcupointRelation,AnatomyLocalizationMap,AnatomyMeridianSinewRelation,MeridianSinew} from '@/lib/anatomy-knowledge/types';
type SearchItem = {kind:'anatomy';id:string;label:string;secondary:string;concept:Concept}|{kind:'acupoint';id:string;label:string;secondary:string;point:Acupoint}|{kind:'sinew';id:string;label:string;secondary:string;sinew:MeridianSinew};
type KnowledgeSelection = {kind:'acupoint';point:Acupoint}|{kind:'sinew';sinew:MeridianSinew}|null;
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[anatomyKo,setAnatomyKo]=useState<AnatomyLocalizationMap>({}),[acupoints,setAcupoints]=useState<Acupoint[]>([]),[acupointCoordinates,setAcupointCoordinates]=useState<AcupointCoordinate[]>([]),[showAcupoints,setShowAcupoints]=useState(false),[meridianSinews,setMeridianSinews]=useState<MeridianSinew[]>([]),[acupointRelations,setAcupointRelations]=useState<AnatomyAcupointRelation[]>([]),[sinewRelations,setSinewRelations]=useState<AnatomyMeridianSinewRelation[]>([]),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null),[knowledge,setKnowledge]=useState<KnowledgeSelection>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch('/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const abort=new AbortController();fetch('/knowledge/anatomy-ko.json',{signal:abort.signal}).then(r=>r.ok?r.json():{}).then(data=>setAnatomyKo(data as AnatomyLocalizationMap)).catch(e=>{if(e.name!=='AbortError')setAnatomyKo({});});return()=>abort.abort();},[]);
 useEffect(()=>{const abort=new AbortController();Promise.all([fetch('/knowledge/acupoints.json',{signal:abort.signal}),fetch('/knowledge/meridian-sinews.json',{signal:abort.signal}),fetch('/knowledge/anatomy-acupoint-relations.json',{signal:abort.signal}),fetch('/knowledge/anatomy-meridian-sinew-relations.json',{signal:abort.signal}),fetch('/knowledge/acupoint-coordinates.json',{signal:abort.signal})]).then(async responses=>Promise.all(responses.map(r=>r.ok?r.json():null))).then(([points,sinews,pointRelations,meridianRelations,coordinateRegistry])=>{setAcupoints((points??[]) as Acupoint[]);setMeridianSinews((sinews??[]) as MeridianSinew[]);setAcupointRelations((pointRelations??[]) as AnatomyAcupointRelation[]);setSinewRelations((meridianRelations??[]) as AnatomyMeridianSinewRelation[]);setAcupointCoordinates(((coordinateRegistry as {points?:AcupointCoordinate[]} | null)?.points??[]) as AcupointCoordinate[]);}).catch(e=>{if(e.name!=='AbortError'){setAcupoints([]);setAcupointCoordinates([]);setMeridianSinews([]);setAcupointRelations([]);setSinewRelations([]);}});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const chosenLocalization=chosen&&anatomyKo[chosen.id]?.nameKo?anatomyKo[chosen.id]:undefined;
 const relatedAcupoints=useMemo(()=>{if(!chosen)return[];return acupointRelations.filter(r=>r.anatomyId===chosen.id).map(relation=>({relation,point:acupoints.find(point=>point.id===relation.acupointId)})).filter((item):item is {relation:AnatomyAcupointRelation;point:Acupoint}=>!!item.point);},[chosen,acupoints,acupointRelations]);
 const relatedSinews=useMemo(()=>{if(!chosen)return[];return sinewRelations.filter(r=>r.anatomyId===chosen.id).map(relation=>({relation,sinew:meridianSinews.find(sinew=>sinew.id===relation.meridianSinewId)})).filter((item):item is {relation:AnatomyMeridianSinewRelation;sinew:MeridianSinew}=>!!item.sinew);},[chosen,meridianSinews,sinewRelations]);
 const results=useMemo<SearchItem[]>(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();const anatomyItems=(term?atlas.concepts.filter(c=>c.id.toLowerCase().includes(term)||anatomySearchTerms(c.name,anatomyKo[c.id]).some(value=>value.toLowerCase().includes(term))):['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x)).map(c=>({kind:'anatomy' as const,id:`anatomy:${c.id}`,label:anatomyKo[c.id]?.nameKo??c.name,secondary:[c.name,anatomyKo[c.id]?.nameKo?anatomyKo[c.id]?.legacyKo:undefined,anatomyKo[c.id]?.nameKo?anatomyKo[c.id]?.hanja:undefined].filter(Boolean).join(' · '),concept:c}));if(!term)return anatomyItems;const pointItems=acupoints.filter(point=>[point.id,point.name.ko,point.name.hanja,point.name.pinyin,point.name.en].filter(Boolean).some(value=>String(value).toLowerCase().includes(term))).map(point=>({kind:'acupoint' as const,id:`acupoint:${point.id}`,label:`${point.id} ${point.name.ko}`,secondary:[point.name.hanja,point.name.pinyin].filter(Boolean).join(' · '),point}));const sinewItems=meridianSinews.filter(sinew=>[sinew.id,sinew.meridian,sinew.name.ko,sinew.name.hanja,sinew.name.en].some(value=>value.toLowerCase().includes(term))).map(sinew=>({kind:'sinew' as const,id:`sinew:${sinew.id}`,label:sinew.name.ko,secondary:`${sinew.name.hanja} · ${sinew.name.en}`,sinew}));return [...anatomyItems,...pointItems,...sinewItems].slice(0,80);},[atlas,query,anatomyKo,acupoints,meridianSinews]);
 const choose=(c:Concept)=>{setKnowledge(null);setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const chooseAcupoint=(point:Acupoint)=>{
  const landmarkIds=[...new Set(acupointRelations.filter(r=>r.acupointId===point.id).flatMap(r=>atlas?.concepts.find(c=>c.id===r.anatomyId)?.elements??[]))];
  setShowAcupoints(true);setChosen(null);setDetails(false);setPanel(null);setKnowledge({kind:'acupoint',point});
  setState(s=>({...s,selected:landmarkIds,isolate:false,rotate:false}));
 };
 const chooseSearch=(item:SearchItem)=>{if(item.kind==='anatomy'){choose(item.concept);return;}if(item.kind==='acupoint'){chooseAcupoint(item.point);return;}setDetails(false);setPanel(null);setKnowledge({kind:'sinew',sinew:item.sinew});};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} acupointCoordinates={acupointCoordinates} showAcupoints={showAcupoints} onSelect={choosePart} onSelectAcupoint={id=>{const point=acupoints.find(item=>item.id===id);if(point)chooseAcupoint(point);}} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> INTERACTIVE ANATOMY</div><h1>Human Atlas<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'2,234'} modeled pieces <span>·</span> BodyParts3D</div></header>
  <nav className="top-actions" aria-label="Explorer panels"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Search anatomy"><Search size={18}/><span>Find a structure</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="About this atlas" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Anatomical layers">
   <div className="panel-heading"><span>Systems</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Close systems"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>All</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>Skeleton</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>Organs</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Show only ${s.name.toLowerCase()}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Show ${s.name.toLowerCase()}`} /></div>)}</div>
   <div className="system-row"><Button variant="ghost" className="system-name" disabled={acupointCoordinates.length===0} title={acupointCoordinates.length?`${acupointCoordinates.length} validated BodyParts3D acupoint markers`:'3D acupoint markers require validated BodyParts3D coordinates'}><span className="system-dot"/>3D 경혈<span className="system-count">{acupointCoordinates.length}</span></Button><Switch checked={showAcupoints} disabled={acupointCoordinates.length===0} onCheckedChange={setShowAcupoints} aria-label="Show validated 3D acupuncture points" /></div><div className="panel-foot"><span>{visibleCount.toLocaleString()} pieces visible</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Hide all</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Find anatomy"><div className="panel-heading"><span>Find a structure</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div><Combobox<SearchItem> items={results} value={null} onValueChange={value=>{if(value)chooseSearch(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={item=>item.label} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="심장, ST36, 족삼리, 족양명위경근…" aria-label="Search anatomy, acupuncture points, and meridian sinews" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>No anatomy or traditional medicine entries match your search.</ComboboxEmpty><ComboboxList>{(item:SearchItem)=><ComboboxItem key={item.id} value={item}><span className="search-result-name">{item.label}<small>{item.secondary}</small></span><span className="small-number">{item.kind==='anatomy'?'해부학':item.kind==='acupoint'?'경혈':'경근'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':'Start with a major organ, or search every named structure.'}</p></section>}
  <nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${v} view`} aria-label={`${v} view`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate body'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name??'SELECTED STRUCTURE'):state.explode>.95?'ANATOMICAL INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':'ADULT HUMAN · MALE'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Open system layers"><Layers3 size={20}/><span>Systems</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Explode anatomy</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Assembled</span><span>Every piece</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Assemble and reset"><RotateCcw size={18}/><span>Reset</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Drag to pan':'Drag to orbit'} <b>·</b> Pinch to zoom <b>·</b> Tap to inspect</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Source & credits <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Preparing the anatomy</strong><span>{progress}% · Loading {atlas?.parts.length.toLocaleString()??'2,234'} pieces</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'ANATOMY'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosenLocalization?.nameKo??chosen?.name}</SheetTitle>{chosenLocalization&&<div className="context-note">{[chosen?.name,chosenLocalization.legacyKo,chosenLocalization.hanja].filter(Boolean).join(' · ')}</div>}</div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosenLocalization?.descriptionKo??(chosen&&selected?explanation(chosen.name,selected.system):'')}</SheetDescription>{chosen&&!chosenLocalization?.descriptionKo&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">System overview · structure identified from source anatomy</span>}<div className="structure-meta"><span>Atlas reference<strong>{chosen?.id}</strong></span><span>Selected pieces<strong>{state.selected.length.toLocaleString()}</strong></span></div>{relatedAcupoints.length>0&&<div className="member-list"><h3>관련 경혈</h3>{relatedAcupoints.map(({point,relation})=><div key={`${chosen?.id}-${point.id}`}><p><strong>{point.id} {point.name.ko} {point.name.hanja}</strong><br/>{point.locationKo}{relation.noteKo&&<><br/><span className="context-note">{relation.noteKo}</span></>}</p></div>)}</div>}{relatedSinews.length>0&&<div className="member-list"><h3>십이경근</h3>{relatedSinews.map(({sinew,relation})=><div key={`${chosen?.id}-${sinew.id}`}><p><strong>{sinew.name.ko} {sinew.name.hanja}</strong><br/><span className="context-note">{sinew.name.en} · {relation.correspondence}</span>{relation.noteKo&&<><br/>{relation.noteKo}</>}</p></div>)}</div>}{selectedParts.length>1&&<div className="member-list"><h3>Included structures</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>And {selectedParts.length-50} more modeled pieces.</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">View anatomical source <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Show surrounding anatomy':'Isolate structure'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>Clear selection</Button></div></SheetContent></Sheet>
  <Sheet open={knowledge!==null} onOpenChange={open=>{if(!open)setKnowledge(null);}}><SheetContent className="detail-sheet glass" showCloseButton={true}>{knowledge?.kind==='acupoint'?<><div className="detail-header"><div className="eyebrow">WHO STANDARD ACUPOINT</div><SheetTitle className="structure-title">{knowledge.point.id} {knowledge.point.name.ko}</SheetTitle><div className="context-note">{knowledge.point.name.hanja}{knowledge.point.name.pinyin?` · ${knowledge.point.name.pinyin}`:''}</div></div><div className="detail-scroll"><SheetDescription className="structure-description">{knowledge.point.locationKo??'표준 경혈 코드와 명칭이 수록되어 있습니다. 위치 설명은 검증된 항목부터 순차적으로 추가됩니다.'}</SheetDescription><div className="structure-meta"><span>경맥<strong>{knowledge.point.meridian}</strong></span><span>좌우<strong>{knowledge.point.laterality==='bilateral'?'양측':'정중선'}</strong></span></div></div></>:knowledge?.kind==='sinew'?<><div className="detail-header"><div className="eyebrow">TWELVE MERIDIAN SINEWS</div><SheetTitle className="structure-title">{knowledge.sinew.name.ko}</SheetTitle><div className="context-note">{knowledge.sinew.name.hanja} · {knowledge.sinew.name.en}</div></div><div className="detail-scroll"><SheetDescription className="structure-description">{knowledge.sinew.overviewKo}</SheetDescription><span className="context-note">고전적 경근 주행과 현대 근육의 대응은 동일 개념이 아니며, 현대해부학 대응은 별도 근거가 있는 경우에만 해석적 관계로 표시합니다.</span></div></>:null}</SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">SOURCE & SCOPE</div><SheetTitle className="structure-title">A body, revealed.</SheetTitle><SheetDescription>Explore the adult male reference anatomy from BodyParts3D.</SheetDescription><div className="about-copy"><p><strong>Male · BodyParts3D</strong><br/>2,234 individual meshes and 3,432 named concepts from an adult male reference anatomy.</p><p>This reference does not contain every human structure or variation. Named concepts can contain multiple pieces; each source mesh is rendered once.</p><p>Colors and system groupings are designed for exploration. The geometry is simplified for the web, and short explanations provide general educational context. This is an anatomical reference, not a diagnostic or surgical tool.</p><h3>Source</h3><p>BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">Dataset license <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">Original geometry & metadata <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">Read the source publication <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
